implementazione alcune query sql problemi con addNode() in sqlDatamanager:
java.sql.SQLException: Parameter index out of range (9 > number of parameters, which is 8).